---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# Tasks for role edx_ansible
#
# Overview:
#
# This is an edx_ansible role that installs edx_ansible :)
# The purpose is to install edx_ansible on a server so
# that it can be updated locally.
#
# This role will also drop some helper scripts that
# for running edx_ansible tasks
#
# Example play:
#
#
#
- name: Create application user
  user:
    name: "{{ edx_ansible_user }}"
    home: "{{ edx_ansible_app_dir }}"
    createhome: no
    shell: /bin/false
  tags:
    - install:base

- name: Create edx_ansible app and venv dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ edx_ansible_user }}"
    group: "{{ common_web_group }}"
  with_items:
    - "{{ edx_ansible_app_dir }}"
    - "{{ edx_ansible_data_dir }}"
    - "{{ edx_ansible_venvs_dir }}"
  tags:
    - install:base

- name: Install a bunch of system packages on which edx_ansible relies
  apt:
    name: "{{ edx_ansible_debian_pkgs }}"
    state: present
    update_cache: true
  tags:
    - install:system-requirements

# Pip for Python2.7 is not included in the Ubuntu 20.04 repositories
# We’ll be installing pip for Python2.7 using the get-pip.py script
- name: Download pip installer
  get_url:
    url=https://bootstrap.pypa.io/get-pip.py
    dest=/tmp/get-pip.py
    mode=0440
  when: ansible_distribution_release == 'focal'
  tags:
    - install:system-requirements

- name: Install pip
  command: /usr/bin/python2.7 /tmp/get-pip.py
  when: ansible_distribution_release == 'focal'
  tags:
    - install:system-requirements

- include: deploy.yml
  tags:
    - deploy
